# Generated by Django 5.1.1 on 2024-09-27 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeruser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
