# Generated by Django 5.1.1 on 2024-09-27 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0002_registeruser_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registeruser',
            name='is_active',
        ),
    ]
