# Generated by Django 5.1.1 on 2024-09-28 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authApp', '0003_remove_registeruser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeruser',
            name='groups',
            field=models.ManyToManyField(related_name='custom_user_set', to='auth.group'),
        ),
        migrations.AddField(
            model_name='registeruser',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='registeruser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='registeruser',
            name='user_permissions',
            field=models.ManyToManyField(related_name='custom_user_set', to='auth.permission'),
        ),
        migrations.AlterField(
            model_name='registeruser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='registeruser',
            name='image',
            field=models.FileField(blank=True, upload_to='assets/image/'),
        ),
        migrations.AlterField(
            model_name='registeruser',
            name='mobileno',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='registeruser',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
