# Generated by Django 5.1.1 on 2024-09-28 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppyyApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='product_id',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='product_name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
